sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-004
env:
  global:
    -
      # LTD_AWS_ID
      secure: qWd0ENV6Zv/yAwlPmkOGiZZrI+DA5rv8xTKd/RC91IK5g78/Q7hpCTi5zNy3vpj/VozQjcgk5gXm4XEix+joplyKNdN6TGcuzcAzb/3MygKkJGepCRY0ADpYNgiyz/imGJf65icHZAAInpPGPmUkaSzig9dUOTnjN2ARypBe2TgmAlwPeunOsTPhzzn9C9wB8FsIIJgbeb0d0uRuxmkZd9uhvTekLQpIk4oae8la+wJksquHy/raHhoDsU/MFkZ7ShmRam+XDGY13AatRd+XxnYKi/+2th511y/sbDeBy2VGpI5r5RkMQg+dXsrijOkbRflsEpkaLuOwB931QPlQfJuHDQWYaBkp1aKbhwUlWjW+/g9D3yeUBzkEvmIaVdAiOGnFg/l+ks7NXBpVKUFXANYg/s9KIrKsfpguLggJi9+9teTzSe1KJJQHJ33A91nqUjtAnc3y7XpaFzc/Vz3g5WJ3fkkyT2xXZb/6sHSqV1qkt8IbsyX/ENeXDjG+gFX3QGcFY3v/4tpDus96fAGnshnxMiNOMv73z5DXYUEHx5eRcJe0Wn5cc6KzLwKsAKUdVnQ4dWRFDpwk33J2ef6M4kc0X3IHX/Uh8o0b4RLtq2dLb0uhOz0FaNulJ72I31G/XX4PW/5aLQPYc7WR8Gp/gC2ac6sZUxQ/KlVS78fMLpg=
    -
      # LTD_AWS_SECRET
      secure: jD+Z+v16VRTXvDGePtmBzIBgfilDeaI66VQ+ji3GLVzHaG9227Wp65oG14ZUMk1ePBl81lIspnqHLOcF1aK4xC+AUcm6g1ClGcXv+N9itF1S5LGKXRwmbr4lOdSnlgrLiWR4n/Zfv1YmrjC1faZb2a9triw59lxW5Pexwgzk4ZxpR2E2LiqKviMAwmD2L43yorgEA0KV4aCeADYzFV2dAxTzno3zAIICkdnrsSPZgMPoge0+P+cIeIH2n6WT+2ZqEJdHSx2E3EiGAjMTJRKjhaCq5Tefh8aWk1r/9MTeCMqd5vAJQTx2QaqCb9oaICCvBlJE5H8KgXZ6dQr6/zsaHr/6GuMHUS+f1t2vp+vgZdWF9ScPV1NRCoigo/3recHFmil+Pi0f0XYe3fluzLJzgw/ZtRcoFKOJIJnFCSNl4kpwyYF7UZOANjzw2Xvo5t0hHoqNpWtD7en4eMtOPpe7PojsQrgfSaKg/MbQ46CSrWsVjAu0xbEwmqTfqhJVGN6J+dv7xAI6tHONjnBXGOHm7UUabXMRhv8SLvIl+7ROeRNbLF+3EpajFonfiRXbtaw2zIhNUEn6Tfj1Pft9f3Fy8sP0znmNizz6My8nl2qnIOfVoN2n91aGdKdkpieVVhkXJpsHmyL5NCkCpPLEJYuNrL6CGK2z6C+OrUYzyRODbfc=
    -
      # LTD_USERNAME
      secure: P1MOk+eRSagmMwOmPCmlRAWldFp6L+Z0W+MoJDajPSrv35axZthBfdBywPklVGSsqcHihsofHYDBGGlQV+aYQYjoENIELzJAefOp4k7f1gWuMidE01uQtMoxO7eZPJDsudjjk4WU5WPA9HFzjXkQFE/Ymxp+P5ElRuL7kDz+F6ZTuOrM6+u6J4iFiNq6bXnkKNZXTKpe6h+1wo9yc9AQ4AygfH4v+D0YTNYipwG5f0r911oQ9Alj7E1TU75+LMqNtUHs+Vt17Dj4SvS2jYDywEwEHO90jYKNJJvrtXSY4FS7OR72YoXURfinj60q6iRlXCOFFl+MSazti71rWYNwvnOyGoyA8CQyPFsaE8Rlhtc1HdNQMUOM7mwr0unwazNj1W+xOgaMOKpQZ0PVXJNhU1FZnVlkGHtgCd0axQgO9K2788yp/uUG4f+Yi2H0oQl+En1WaYbBnGmzYbdilw/D5sBIRpa/R8b0DJ/jN97gzqE4IMPVinv7PsOgnQ4YfGEA+lbOKdXSYBF2U+JR8EVhJFPis5AV5/tVIBKB9TRroBtpYXcmckBlE8zHoGpYn7gaANIXsnvxN95Kbj3QxkL6YFURQ0jHoWp0ciALfAPrWFCkgYl1VTpWyMBCAtnwtnqxpz5SUXpsE8XcKSAe4IIfBjq0ANWejGQzLroPD8+seuU=
    -
      # LTD_PASSWORD
      secure: wMsb0wD8qwF/UCvK0hGyFHPOH5P9BXm0oED1perSM+RZfjmSlu0hc2Op4ECn4AadfhYj/zWKZ3ipp7xylnCXa8915YFlEEey4d4CQtGNgYtEQ05RQ0DR2t7XC574dDuCgOWXfa2DNKyNoa5L+JVsfHiD2eq1B/CyGiD0HO/9v0w/4dSVtSmmPc8dDLmXacvzsyHVYUFaASJKe2BqY6BA59A7sidzFhlyUYuG/OsQR6EkrM1jyK6UqRYucj2NUtZIt0poZ00G1qUaCAWDWrvHBpH8FVljf/7J3OSW+xr3P4v0VXerIMFpcUKZj6OgIvPp5jAEQ0Py9HnPXJoG0ETJeeruelzwec3eYeMIGjsOTKDNdnElTUhgf9bKwYpDlsA6RKnLRxt8IhwVaGdIEk3CHNTT0GRTu/w0viTmIAAwO7c+C+4q1llWzj16ONVWQCHN6ilToeLGsGE0CZ1Is2EN8GkuVK+a79fF+fjFLIuemwfQUeT8BWbRXZdfCm1MYmvrWrvnLOpeB2p6ZtyKqYxqt312Ve87jAHKZY/JGZp8UzeOh2q5NE5E0l44RfXAHAXvxWtrCXKUmBf+hfnhNra9iR6hwwyMr0L5vxD0WdrzhN6fK/Vy+2IsNAcGbfKBak+GdYmsmto63QxbeTFmzreAc1zOBaHKTsvHaKQWarZlZWA=
